name: desktop-helpers
version: 1
summary: Various technology desktop helpers for snapcraft
description: |
  Helpers for gtk2, gtk3, qt4 and qt5 or gnome-platform and glib minimal launchers.
  It brings the necessary code and exports for binding and using those
  desktop technologies in a relocatable fashion, enabling binding with
  global desktop theme, icon theme, image caching, fonts, mimetype handlers
  application global menu and gsettings integration.
  It also brings basics ubuntu dependency packages.
  .
  Usage:
    1. add "after: [desktop-<technology>]" to your launcher:
       - gtk2, gtk3, qt4 and qt5 corresponds to their respective toolkit
         main dependencies and default choices.
       - gnome-platform is similar to gtk3 without the extra depends, it's
         meant to be used with the gnome platform which already includes those.
       - ubuntu-app-platform corresponds to the shared platform snap use.
       - glib-only enables to compile mime types and gsettings infos. If you
         added your own graphical drivers, it will link them as well.
    2. prepend your command with "desktop-launch", like:
       commands: "desktop-launch foo" if foo is in $PATH. You can as well
       specify: "desktop-launch $SNAP/foo".
    3. add needed plugs to your application:
       - for graphical application:
         plugs: [x11 (or unity7 for appmenu integration)]. Think about adding
         opengl if you need hw acceleration.
       - if your application needs access to sound:
         plugs: [pulseaudio]
       - accessing to user's home directory:
         plugs: [home]
       - read/write to gsettings:
         plugs: [gsettings, home]
         (note that the home plug is needed to read new value)
       - use of the shared platform snap content, first define the plug:
           plugs:
             platform:
               content: ubuntu-app-platform1
               default-provider: ubuntu-app-platform
               interface: content
               target: ubuntu-app-platform
         and then make your apps use it:
           plugs: [platform]
       - access to Mir:
           plugs:
             mir:
             mir-libs:
               default-provider: mir-libs
               interface: content
               target: mir-libs
       - similarly for the gnome platform based apps
          plugs:
              gnome-3-24-platform:
                default-provider: gnome-3-24:gnome-3-24-platform
                interface: content
                target: gnome-platform
         and then make your apps use it:
           plugs: [gnome-platform]
         Note that an empty "gnome-platform" directory will be created for you
         in your snap.

confinement: strict

parts:
  desktop:
    plugin: nil
  gtk2:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - libappindicator1
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  gtk3:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  qt4:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt4"]
    build-packages:
      - libqt4-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqtgui4
      - libgdk-pixbuf2.0-0
      - libqt4-svg # for loading icon themes which are svg
      - appmenu-qt
      - locales-all
      - sni-qt
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  qt5:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - appmenu-qt5
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  glib-only:
    source: .
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
  desktop/gtk2:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - libappindicator1
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop/gtk3:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop/qt4:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt4"]
    build-packages:
      - libqt4-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqtgui4
      - libgdk-pixbuf2.0-0
      - libqt4-svg # for loading icon themes which are svg
      - appmenu-qt
      - locales-all
      - sni-qt
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop/qt5:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - appmenu-qt5
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop/glib-only:
    source: .
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
  desktop-gtk2:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - locales-all
      - libappindicator1
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop-gtk3:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop-qt4:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt4"]
    build-packages:
      - libqt4-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqtgui4
      - libgdk-pixbuf2.0-0
      - libqt4-svg # for loading icon themes which are svg
      - appmenu-qt
      - locales-all
      - sni-qt
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop-qt5:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - appmenu-qt5
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  desktop-glib-only:
    source: .
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
  desktop-gnome-platform:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    install: mkdir -p $SNAPCRAFT_PART_INSTALL/gnome-platform
  desktop-ubuntu-app-platform:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    # developer should use stable-phone-overlay PPA for Qt 5.6 to match the platform snap
    build-packages:
      - dpkg-dev
      - libcontent-hub-dev
      - libmediascanner-2.0-dev
      - libqt5sensors5-dev
      - libqt5websockets5-dev
      - libthumbnailer-qt-dev
      - libubuntu-download-manager-client-dev
      - libubuntutoolkit5-dev
      - libubuntumetrics5-dev
      - libubuntugestures5-dev
      - qtbase5-dev
      - qtconnectivity5-dev
      - qtdeclarative5-dev
      - qtlocation5-dev
      - qtmultimedia5-dev
      - qtpim5-dev
      - qtpositioning5-dev
    # No staged packages, they are in the platform snap
